{
  recipes = {
    recipes = {
      [ "ironchest:iron_shulker_box_purple:3" ] = {
        maxCount = 1,
        ingredients = {
          "galacticraftcore:basic_item:3",
          "galacticraftcore:basic_item:3",
          "galacticraftcore:basic_item:3",
          [ 7 ] = "galacticraftcore:basic_item:3",
          [ 9 ] = "galacticraftcore:basic_item:3",
          [ 10 ] = "galacticraftcore:basic_item:3",
          [ 11 ] = "galacticraftcore:basic_item:3",
          [ 5 ] = "galacticraftcore:basic_item:3",
          [ 6 ] = "minecraft:purple_shulker_box:0",
        },
        count = 1,
      },
      [ "ironchest:iron_chest:6" ] = {
        count = 1,
        ingredients = {
          "minecraft:obsidian:0",
          "minecraft:obsidian:0",
          "minecraft:obsidian:0",
          [ 7 ] = "minecraft:obsidian:0",
          [ 9 ] = "minecraft:obsidian:0",
          [ 10 ] = "minecraft:obsidian:0",
          [ 11 ] = "minecraft:obsidian:0",
          [ 5 ] = "minecraft:obsidian:0",
          [ 6 ] = "ironchest:iron_chest:2",
        },
      },
      [ "ironchest:copper_iron_chest_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:glass:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:glass:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:glass:0",
          [ 6 ] = "galacticraftcore:basic_item:3",
        },
        count = 1,
      },
      [ "ironchest:iron_chest:2" ] = {
        count = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:diamond:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 6 ] = "ironchest:iron_chest:1",
        },
      },
      [ "ironchest:iron_gold_chest_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
      },
      [ "ironchest:wood_iron_chest_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:planks:0",
        },
        count = 1,
      },
      [ "ironchest:iron_chest:5" ] = {
        count = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:glass:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:glass:0",
          [ 6 ] = "ironchest:iron_chest:2",
        },
      },
      [ "ironchest:wood_copper_chest_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "galacticraftcore:basic_item:3",
          "galacticraftcore:basic_item:3",
          "galacticraftcore:basic_item:3",
          [ 7 ] = "galacticraftcore:basic_item:3",
          [ 9 ] = "galacticraftcore:basic_item:3",
          [ 10 ] = "galacticraftcore:basic_item:3",
          [ 11 ] = "galacticraftcore:basic_item:3",
          [ 5 ] = "galacticraftcore:basic_item:3",
          [ 6 ] = "minecraft:planks:0",
        },
        count = 1,
      },
      [ "ironchest:iron_gold_shulker_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "ironchest:gold_diamond_chest_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:diamond:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 6 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "ironchest:iron_shulker_box_purple:2" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:diamond:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 6 ] = "ironchest:iron_shulker_box_purple:1",
        },
        count = 1,
      },
      [ "ironchest:gold_diamond_shulker_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:diamond:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:glass:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:diamond:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:glass:0",
          [ 6 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "ironchest:copper_iron_shulker_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "galacticraftcore:basic_item:3",
        },
        count = 1,
      },
      [ "ironchest:diamond_crystal_shulker_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:obsidian:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:glass:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:glass:0",
          [ 6 ] = "minecraft:glass:0",
        },
        count = 1,
      },
      [ "ironchest:iron_shulker_box_purple:5" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:glass:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:glass:0",
          [ 6 ] = "ironchest:iron_shulker_box_purple:2",
        },
        count = 1,
      },
      [ "ironchest:iron_chest:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:chest:0",
        },
      },
      [ "ironchest:diamond_obsidian_chest_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:obsidian:0",
          "minecraft:obsidian:0",
          "minecraft:obsidian:0",
          [ 7 ] = "minecraft:obsidian:0",
          [ 9 ] = "minecraft:obsidian:0",
          [ 10 ] = "minecraft:obsidian:0",
          [ 11 ] = "minecraft:obsidian:0",
          [ 5 ] = "minecraft:obsidian:0",
          [ 6 ] = "minecraft:glass:0",
        },
        count = 1,
      },
      [ "ironchest:iron_chest:1" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "ironchest:iron_chest:0",
        },
      },
      [ "ironchest:iron_shulker_box_purple:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:purple_shulker_box:0",
        },
        count = 1,
      },
      [ "ironchest:vanilla_iron_shulker_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:shulker_shell:0",
        },
        count = 1,
      },
      [ "ironchest:iron_shulker_box_purple:6" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:obsidian:0",
          "minecraft:obsidian:0",
          "minecraft:obsidian:0",
          [ 7 ] = "minecraft:obsidian:0",
          [ 9 ] = "minecraft:obsidian:0",
          [ 10 ] = "minecraft:obsidian:0",
          [ 11 ] = "minecraft:obsidian:0",
          [ 5 ] = "minecraft:obsidian:0",
          [ 6 ] = "ironchest:iron_shulker_box_purple:2",
        },
        count = 1,
      },
      [ "ironchest:diamond_crystal_chest_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:glass:0",
          [ 9 ] = "minecraft:glass:0",
          [ 10 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:glass:0",
          [ 5 ] = "minecraft:glass:0",
          [ 6 ] = "minecraft:obsidian:0",
        },
        count = 1,
      },
      [ "ironchest:vanilla_copper_shulker_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "galacticraftcore:basic_item:3",
          "galacticraftcore:basic_item:3",
          "galacticraftcore:basic_item:3",
          [ 7 ] = "galacticraftcore:basic_item:3",
          [ 9 ] = "galacticraftcore:basic_item:3",
          [ 10 ] = "galacticraftcore:basic_item:3",
          [ 11 ] = "galacticraftcore:basic_item:3",
          [ 5 ] = "galacticraftcore:basic_item:3",
          [ 6 ] = "minecraft:shulker_shell:0",
        },
        count = 1,
      },
      [ "ironchest:iron_shulker_box_purple:1" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "ironchest:iron_shulker_box_purple:0",
        },
        count = 1,
      },
      [ "ironchest:diamond_obsidian_shulker_upgrade:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:obsidian:0",
          "minecraft:glass:0",
          "minecraft:obsidian:0",
          [ 7 ] = "minecraft:obsidian:0",
          [ 9 ] = "minecraft:obsidian:0",
          [ 10 ] = "minecraft:obsidian:0",
          [ 11 ] = "minecraft:obsidian:0",
          [ 5 ] = "minecraft:obsidian:0",
          [ 6 ] = "minecraft:obsidian:0",
        },
        count = 1,
      },
      [ "ironchest:iron_chest:7" ] = {
        count = 1,
        ingredients = {
          "minecraft:dirt:0",
          "minecraft:dirt:0",
          "minecraft:dirt:0",
          [ 7 ] = "minecraft:dirt:0",
          [ 9 ] = "minecraft:dirt:0",
          [ 10 ] = "minecraft:dirt:0",
          [ 11 ] = "minecraft:dirt:0",
          [ 5 ] = "minecraft:dirt:0",
          [ 6 ] = "minecraft:chest:0",
        },
      },
    },
    name = "ironchest",
    version = "MC 1.12",
  },
  names = {
    [ "ironchest:iron_shulker_box_purple:3" ] = "Purple Copper Shulker Box",
    [ "ironchest:iron_shulker_box_purple:2" ] = "Purple Diamond Shulker Box",
    [ "ironchest:diamond_obsidian_shulker_upgrade:0" ] = "Diamond to Obsidian Shulker Box Upgrade",
    [ "ironchest:gold_diamond_shulker_upgrade:0" ] = "Gold to Diamond Shulker Box Upgrade",
    [ "ironchest:iron_chest:5" ] = "Crystal Chest",
    [ "ironchest:wood_iron_chest_upgrade:0" ] = "Wood to Iron Chest Upgrade",
    [ "ironchest:iron_chest:7" ] = "DirtChest 9000!",
    [ "ironchest:wood_copper_chest_upgrade:0" ] = "Wood to Copper Chest Upgrade",
    [ "ironchest:diamond_crystal_chest_upgrade:0" ] = "Diamond to Crystal Chest Upgrade",
    [ "ironchest:gold_diamond_chest_upgrade:0" ] = "Gold to Diamond Chest Upgrade",
    [ "ironchest:vanilla_iron_shulker_upgrade:0" ] = "Vanilla to Iron Shulker Box Upgrade",
    [ "ironchest:iron_shulker_box_purple:6" ] = "Purple Obsidian Shulker Box",
    [ "ironchest:copper_iron_shulker_upgrade:0" ] = "Copper to Iron Shulker Box Upgrade",
    [ "ironchest:diamond_crystal_shulker_upgrade:0" ] = "Diamond to Crystal Shulker Box Upgrade",
    [ "ironchest:iron_shulker_box_purple:5" ] = "Purple Crystal Shulker Box",
    [ "ironchest:iron_chest:0" ] = "Iron Chest",
    [ "ironchest:diamond_obsidian_chest_upgrade:0" ] = "Diamond to Obsidian Chest Upgrade",
    [ "ironchest:vanilla_copper_shulker_upgrade:0" ] = "Vanilla to Copper Shulker Box Upgrade",
    [ "ironchest:iron_shulker_box_purple:0" ] = "Purple Iron Shulker Box",
    [ "ironchest:iron_gold_shulker_upgrade:0" ] = "Iron to Gold Shulker Box Upgrade",
    [ "ironchest:iron_chest:6" ] = "Obsidian Chest",
    [ "ironchest:iron_chest:1" ] = "Gold Chest",
    [ "ironchest:iron_gold_chest_upgrade:0" ] = "Iron to Gold Chest Upgrade",
    [ "ironchest:iron_chest:2" ] = "Diamond Chest",
    [ "ironchest:copper_iron_chest_upgrade:0" ] = "Copper to Iron Chest Upgrade",
    [ "ironchest:iron_shulker_box_purple:1" ] = "Purple Gold Shulker Box",
  },
}
