{
  recipes = {
    recipes = {
      [ "minecraft:leather_chestplate:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:leather:0",
          [ 7 ] = "minecraft:leather:0",
          [ 9 ] = "minecraft:leather:0",
          [ 3 ] = "minecraft:leather:0",
          [ 11 ] = "minecraft:leather:0",
          [ 5 ] = "minecraft:leather:0",
          [ 6 ] = "minecraft:leather:0",
          [ 10 ] = "minecraft:leather:0",
        },
        count = 1,
      },
      [ "minecraft:banner:5" ] = {
        ingredients = {
          "minecraft:wool:10",
          "minecraft:wool:10",
          "minecraft:wool:10",
          [ 6 ] = "minecraft:wool:10",
          [ 7 ] = "minecraft:wool:10",
          [ 5 ] = "minecraft:wool:10",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:fishing_rod:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 7 ] = "minecraft:string:0",
          [ 9 ] = "minecraft:stick:0",
          [ 3 ] = "minecraft:stick:0",
          [ 11 ] = "minecraft:string:0",
          [ 6 ] = "minecraft:stick:0",
        },
        count = 1,
      },
      [ "minecraft:iron_axe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:concrete_powder:10" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:5",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:chest_minecart:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:chest:0",
          [ 5 ] = "minecraft:minecart:0",
        },
        count = 1,
      },
      [ "minecraft:concrete_powder:12" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:3",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:stained_hardened_clay:1" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:14",
        },
      },
      [ "minecraft:stained_hardened_clay:13" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:2",
        },
      },
      [ "minecraft:stone_slab2:0" ] = {
        count = 6,
        ingredients = {
          [ 9 ] = "minecraft:red_sandstone:0",
          [ 10 ] = "minecraft:red_sandstone:0",
          [ 11 ] = "minecraft:red_sandstone:0",
        },
      },
      [ "minecraft:concrete_powder:7" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:8",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:wooden_pickaxe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:planks:0",
          "minecraft:planks:0",
          "minecraft:planks:0",
          [ 6 ] = "minecraft:stick:0",
          [ 10 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:acacia_boat:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:planks:4",
          [ 3 ] = "minecraft:planks:4",
          [ 7 ] = "minecraft:planks:4",
          [ 5 ] = "minecraft:planks:4",
          [ 6 ] = "minecraft:planks:4",
        },
        count = 1,
      },
      [ "minecraft:banner:7" ] = {
        ingredients = {
          "minecraft:wool:8",
          "minecraft:wool:8",
          "minecraft:wool:8",
          [ 6 ] = "minecraft:wool:8",
          [ 7 ] = "minecraft:wool:8",
          [ 5 ] = "minecraft:wool:8",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:wooden_axe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:planks:0",
          "minecraft:planks:0",
          [ 6 ] = "minecraft:planks:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:stained_hardened_clay:14" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:1",
        },
      },
      [ "minecraft:stone_hoe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:cobblestone:0",
          "minecraft:cobblestone:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:slime:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:slime_ball:0",
          "minecraft:slime_ball:0",
          "minecraft:slime_ball:0",
          [ 7 ] = "minecraft:slime_ball:0",
          [ 9 ] = "minecraft:slime_ball:0",
          [ 10 ] = "minecraft:slime_ball:0",
          [ 11 ] = "minecraft:slime_ball:0",
          [ 5 ] = "minecraft:slime_ball:0",
          [ 6 ] = "minecraft:slime_ball:0",
        },
      },
      [ "minecraft:leather_leggings:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:leather:0",
          "minecraft:leather:0",
          "minecraft:leather:0",
          [ 9 ] = "minecraft:leather:0",
          [ 7 ] = "minecraft:leather:0",
          [ 5 ] = "minecraft:leather:0",
          [ 11 ] = "minecraft:leather:0",
        },
        count = 1,
      },
      [ "minecraft:banner:15" ] = {
        maxCount = 16,
        ingredients = {
          "minecraft:wool:0",
          "minecraft:wool:0",
          "minecraft:wool:0",
          [ 6 ] = "minecraft:wool:0",
          [ 7 ] = "minecraft:wool:0",
          [ 5 ] = "minecraft:wool:0",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
      },
      [ "minecraft:iron_chestplate:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 3 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:red_mushroom_block:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:red_mushroom:0",
          "minecraft:red_mushroom:0",
          [ 5 ] = "minecraft:red_mushroom:0",
          [ 6 ] = "minecraft:red_mushroom:0",
        },
      },
      [ "minecraft:golden_carrot:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_nugget:0",
          "minecraft:gold_nugget:0",
          "minecraft:gold_nugget:0",
          [ 7 ] = "minecraft:gold_nugget:0",
          [ 9 ] = "minecraft:gold_nugget:0",
          [ 10 ] = "minecraft:gold_nugget:0",
          [ 11 ] = "minecraft:gold_nugget:0",
          [ 5 ] = "minecraft:gold_nugget:0",
          [ 6 ] = "minecraft:carrot:0",
        },
      },
      [ "minecraft:golden_sword:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:banner:11" ] = {
        ingredients = {
          "minecraft:wool:4",
          "minecraft:wool:4",
          "minecraft:wool:4",
          [ 6 ] = "minecraft:wool:4",
          [ 7 ] = "minecraft:wool:4",
          [ 5 ] = "minecraft:wool:4",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:concrete_powder:0" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:15",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:fermented_spider_eye:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:spider_eye:0",
          "minecraft:brown_mushroom:0",
          [ 5 ] = "minecraft:sugar:0",
        },
      },
      [ "minecraft:banner:8" ] = {
        ingredients = {
          "minecraft:wool:7",
          "minecraft:wool:7",
          "minecraft:wool:7",
          [ 6 ] = "minecraft:wool:7",
          [ 7 ] = "minecraft:wool:7",
          [ 5 ] = "minecraft:wool:7",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:banner:0" ] = {
        ingredients = {
          "minecraft:wool:15",
          "minecraft:wool:15",
          "minecraft:wool:15",
          [ 6 ] = "minecraft:wool:15",
          [ 7 ] = "minecraft:wool:15",
          [ 5 ] = "minecraft:wool:15",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:concrete_powder:4" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:11",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:diamond_helmet:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:diamond:0",
          "minecraft:diamond:0",
          "minecraft:diamond:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 7 ] = "minecraft:diamond:0",
        },
        count = 1,
      },
      [ "minecraft:cookie:0" ] = {
        count = 8,
        ingredients = {
          "minecraft:wheat:0",
          "minecraft:dye:3",
          "minecraft:wheat:0",
        },
      },
      [ "minecraft:golden_chestplate:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 3 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:spruce_boat:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:planks:1",
          [ 3 ] = "minecraft:planks:1",
          [ 7 ] = "minecraft:planks:1",
          [ 5 ] = "minecraft:planks:1",
          [ 6 ] = "minecraft:planks:1",
        },
        count = 1,
      },
      [ "minecraft:compass:0" ] = {
        count = 1,
        ingredients = {
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 2 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:redstone:0",
        },
      },
      [ "minecraft:wool:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:string:0",
          "minecraft:string:0",
          [ 5 ] = "minecraft:string:0",
          [ 6 ] = "minecraft:string:0",
        },
      },
      [ "minecraft:banner:9" ] = {
        ingredients = {
          "minecraft:wool:6",
          "minecraft:wool:6",
          "minecraft:wool:6",
          [ 6 ] = "minecraft:wool:6",
          [ 7 ] = "minecraft:wool:6",
          [ 5 ] = "minecraft:wool:6",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:dark_oak_boat:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:planks:5",
          [ 3 ] = "minecraft:planks:5",
          [ 7 ] = "minecraft:planks:5",
          [ 5 ] = "minecraft:planks:5",
          [ 6 ] = "minecraft:planks:5",
        },
        count = 1,
      },
      [ "minecraft:golden_rail:0" ] = {
        count = 6,
        ingredients = {
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 3 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:stick:0",
          [ 10 ] = "minecraft:redstone:0",
        },
      },
      [ "minecraft:diamond_axe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:diamond:0",
          "minecraft:diamond:0",
          [ 6 ] = "minecraft:diamond:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:diamond_chestplate:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:diamond:0",
          [ 7 ] = "minecraft:diamond:0",
          [ 9 ] = "minecraft:diamond:0",
          [ 3 ] = "minecraft:diamond:0",
          [ 11 ] = "minecraft:diamond:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 6 ] = "minecraft:diamond:0",
          [ 10 ] = "minecraft:diamond:0",
        },
        count = 1,
      },
      [ "minecraft:golden_pickaxe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:stick:0",
          [ 10 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:stained_hardened_clay:5" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:10",
        },
      },
      [ "minecraft:concrete_powder:13" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:2",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:rail:0" ] = {
        count = 16,
        ingredients = {
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 3 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:arrow:0" ] = {
        count = 4,
        ingredients = {
          "minecraft:flint:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:feather:0",
        },
      },
      [ "minecraft:stained_hardened_clay:3" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:12",
        },
      },
      [ "minecraft:diamond_hoe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:diamond:0",
          "minecraft:diamond:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:red_sandstone_stairs:0" ] = {
        count = 4,
        ingredients = {
          "minecraft:red_sandstone:0",
          [ 9 ] = "minecraft:red_sandstone:0",
          [ 10 ] = "minecraft:red_sandstone:0",
          [ 11 ] = "minecraft:red_sandstone:0",
          [ 5 ] = "minecraft:red_sandstone:0",
          [ 6 ] = "minecraft:red_sandstone:0",
        },
      },
      [ "minecraft:banner:1" ] = {
        ingredients = {
          "minecraft:wool:14",
          "minecraft:wool:14",
          "minecraft:wool:14",
          [ 6 ] = "minecraft:wool:14",
          [ 7 ] = "minecraft:wool:14",
          [ 5 ] = "minecraft:wool:14",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:iron_shovel:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:stone_axe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:cobblestone:0",
          "minecraft:cobblestone:0",
          [ 6 ] = "minecraft:cobblestone:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:paper:0" ] = {
        count = 3,
        ingredients = {
          "minecraft:reeds:0",
          "minecraft:reeds:0",
          "minecraft:reeds:0",
        },
      },
      [ "minecraft:purpur_pillar:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:purpur_slab:0",
          [ 5 ] = "minecraft:purpur_slab:0",
        },
      },
      [ "minecraft:minecart:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          [ 3 ] = "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:wooden_hoe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:planks:0",
          "minecraft:planks:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:stained_hardened_clay:7" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:8",
        },
      },
      [ "minecraft:diamond_sword:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:diamond:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:rabbit_stew:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 7 ] = "minecraft:red_mushroom:0",
          [ 2 ] = "minecraft:cooked_rabbit:0",
          [ 10 ] = "minecraft:bowl:0",
          [ 5 ] = "minecraft:carrot:0",
          [ 6 ] = "minecraft:baked_potato:0",
        },
        count = 1,
      },
      [ "minecraft:concrete_powder:6" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:9",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:armor_stand:0" ] = {
        maxCount = 16,
        ingredients = {
          "minecraft:stick:0",
          "minecraft:stick:0",
          "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
          [ 10 ] = "minecraft:stone_slab:0",
          [ 11 ] = "minecraft:stick:0",
          [ 6 ] = "minecraft:stick:0",
        },
        count = 1,
      },
      [ "minecraft:stone_pickaxe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:cobblestone:0",
          "minecraft:cobblestone:0",
          "minecraft:cobblestone:0",
          [ 6 ] = "minecraft:stick:0",
          [ 10 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:concrete_powder:14" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:1",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:banner:2" ] = {
        ingredients = {
          "minecraft:wool:13",
          "minecraft:wool:13",
          "minecraft:wool:13",
          [ 6 ] = "minecraft:wool:13",
          [ 7 ] = "minecraft:wool:13",
          [ 5 ] = "minecraft:wool:13",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:stained_hardened_clay:10" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:5",
        },
      },
      [ "minecraft:observer:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:cobblestone:0",
          "minecraft:cobblestone:0",
          "minecraft:cobblestone:0",
          [ 7 ] = "minecraft:quartz:0",
          [ 9 ] = "minecraft:cobblestone:0",
          [ 10 ] = "minecraft:cobblestone:0",
          [ 11 ] = "minecraft:cobblestone:0",
          [ 5 ] = "minecraft:redstone:0",
          [ 6 ] = "minecraft:redstone:0",
        },
      },
      [ "minecraft:purpur_stairs:0" ] = {
        count = 4,
        ingredients = {
          "minecraft:purpur_block:0",
          [ 9 ] = "minecraft:purpur_block:0",
          [ 10 ] = "minecraft:purpur_block:0",
          [ 11 ] = "minecraft:purpur_block:0",
          [ 5 ] = "minecraft:purpur_block:0",
          [ 6 ] = "minecraft:purpur_block:0",
        },
      },
      [ "minecraft:diamond_shovel:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:diamond:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:stained_hardened_clay:15" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:0",
        },
      },
      [ "minecraft:concrete_powder:8" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:7",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:banner:3" ] = {
        ingredients = {
          "minecraft:wool:12",
          "minecraft:wool:12",
          "minecraft:wool:12",
          [ 6 ] = "minecraft:wool:12",
          [ 7 ] = "minecraft:wool:12",
          [ 5 ] = "minecraft:wool:12",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:stone_shovel:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:cobblestone:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:lead:0" ] = {
        count = 2,
        ingredients = {
          "minecraft:string:0",
          "minecraft:string:0",
          [ 6 ] = "minecraft:slime_ball:0",
          [ 5 ] = "minecraft:string:0",
          [ 11 ] = "minecraft:string:0",
        },
      },
      [ "minecraft:stained_hardened_clay:2" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:13",
        },
      },
      [ "minecraft:detector_rail:0" ] = {
        count = 6,
        ingredients = {
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 3 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:stone_pressure_plate:0",
          [ 10 ] = "minecraft:redstone:0",
        },
      },
      [ "minecraft:banner:10" ] = {
        ingredients = {
          "minecraft:wool:5",
          "minecraft:wool:5",
          "minecraft:wool:5",
          [ 6 ] = "minecraft:wool:5",
          [ 7 ] = "minecraft:wool:5",
          [ 5 ] = "minecraft:wool:5",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:banner:6" ] = {
        ingredients = {
          "minecraft:wool:9",
          "minecraft:wool:9",
          "minecraft:wool:9",
          [ 6 ] = "minecraft:wool:9",
          [ 7 ] = "minecraft:wool:9",
          [ 5 ] = "minecraft:wool:9",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:iron_sword:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:concrete_powder:9" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:6",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:golden_apple:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:apple:0",
        },
      },
      [ "minecraft:shears:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 2 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:stained_hardened_clay:12" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:3",
        },
      },
      [ "minecraft:diamond_boots:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 9 ] = "minecraft:diamond:0",
          [ 7 ] = "minecraft:diamond:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 11 ] = "minecraft:diamond:0",
        },
        count = 1,
      },
      [ "minecraft:concrete_powder:15" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:0",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:activator_rail:0" ] = {
        count = 6,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:stick:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:stick:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:redstone_torch:0",
        },
      },
      [ "minecraft:iron_nugget:0" ] = {
        count = 9,
        ingredients = {
          "minecraft:iron_ingot:0",
        },
      },
      [ "minecraft:golden_hoe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:banner:13" ] = {
        ingredients = {
          "minecraft:wool:2",
          "minecraft:wool:2",
          "minecraft:wool:2",
          [ 6 ] = "minecraft:wool:2",
          [ 7 ] = "minecraft:wool:2",
          [ 5 ] = "minecraft:wool:2",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:concrete_powder:11" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:4",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:purple_shulker_box:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:shulker_shell:0",
          [ 5 ] = "minecraft:chest:0",
          [ 9 ] = "minecraft:shulker_shell:0",
        },
      },
      [ "minecraft:concrete_powder:1" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:14",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:banner:14" ] = {
        ingredients = {
          "minecraft:wool:1",
          "minecraft:wool:1",
          "minecraft:wool:1",
          [ 6 ] = "minecraft:wool:1",
          [ 7 ] = "minecraft:wool:1",
          [ 5 ] = "minecraft:wool:1",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:iron_helmet:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:concrete_powder:3" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:12",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:bowl:0" ] = {
        count = 4,
        ingredients = {
          "minecraft:planks:0",
          [ 3 ] = "minecraft:planks:0",
          [ 6 ] = "minecraft:planks:0",
        },
      },
      [ "minecraft:stone_sword:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:cobblestone:0",
          [ 5 ] = "minecraft:cobblestone:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:stained_hardened_clay:0" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:15",
        },
      },
      [ "minecraft:red_nether_brick:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:netherbrick:0",
          "minecraft:nether_wart:0",
          [ 5 ] = "minecraft:nether_wart:0",
          [ 6 ] = "minecraft:netherbrick:0",
        },
      },
      [ "minecraft:golden_leggings:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:magma_cream:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:blaze_powder:0",
          "minecraft:slime_ball:0",
        },
      },
      [ "minecraft:daylight_detector:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:glass:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:quartz:0",
          [ 9 ] = "minecraft:wooden_slab:0",
          [ 10 ] = "minecraft:wooden_slab:0",
          [ 11 ] = "minecraft:wooden_slab:0",
          [ 5 ] = "minecraft:quartz:0",
          [ 6 ] = "minecraft:quartz:0",
        },
      },
      [ "minecraft:magma:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:magma_cream:0",
          "minecraft:magma_cream:0",
          [ 5 ] = "minecraft:magma_cream:0",
          [ 6 ] = "minecraft:magma_cream:0",
        },
      },
      [ "minecraft:golden_boots:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:leather_helmet:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:leather:0",
          "minecraft:leather:0",
          "minecraft:leather:0",
          [ 5 ] = "minecraft:leather:0",
          [ 7 ] = "minecraft:leather:0",
        },
        count = 1,
      },
      [ "minecraft:stained_hardened_clay:11" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:4",
        },
      },
      [ "minecraft:leather_boots:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 9 ] = "minecraft:leather:0",
          [ 7 ] = "minecraft:leather:0",
          [ 5 ] = "minecraft:leather:0",
          [ 11 ] = "minecraft:leather:0",
        },
        count = 1,
      },
      [ "minecraft:jungle_boat:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:planks:3",
          [ 3 ] = "minecraft:planks:3",
          [ 7 ] = "minecraft:planks:3",
          [ 5 ] = "minecraft:planks:3",
          [ 6 ] = "minecraft:planks:3",
        },
        count = 1,
      },
      [ "minecraft:banner:4" ] = {
        ingredients = {
          "minecraft:wool:11",
          "minecraft:wool:11",
          "minecraft:wool:11",
          [ 6 ] = "minecraft:wool:11",
          [ 7 ] = "minecraft:wool:11",
          [ 5 ] = "minecraft:wool:11",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:map:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:paper:0",
          "minecraft:paper:0",
          "minecraft:paper:0",
          [ 7 ] = "minecraft:paper:0",
          [ 9 ] = "minecraft:paper:0",
          [ 10 ] = "minecraft:paper:0",
          [ 11 ] = "minecraft:paper:0",
          [ 5 ] = "minecraft:paper:0",
          [ 6 ] = "minecraft:compass:0",
        },
      },
      [ "minecraft:diamond_leggings:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:diamond:0",
          "minecraft:diamond:0",
          "minecraft:diamond:0",
          [ 9 ] = "minecraft:diamond:0",
          [ 7 ] = "minecraft:diamond:0",
          [ 5 ] = "minecraft:diamond:0",
          [ 11 ] = "minecraft:diamond:0",
        },
        count = 1,
      },
      [ "minecraft:fire_charge:0" ] = {
        count = 3,
        ingredients = {
          "minecraft:gunpowder:0",
          "minecraft:blaze_powder:0",
          [ 5 ] = "minecraft:coal:0",
        },
      },
      [ "minecraft:golden_axe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:stained_hardened_clay:6" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:9",
        },
      },
      [ "minecraft:pumpkin_pie:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:pumpkin:0",
          "minecraft:sugar:0",
          [ 5 ] = "minecraft:egg:0",
        },
      },
      [ "minecraft:stained_hardened_clay:9" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:6",
        },
      },
      [ "minecraft:birch_boat:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:planks:2",
          [ 3 ] = "minecraft:planks:2",
          [ 7 ] = "minecraft:planks:2",
          [ 5 ] = "minecraft:planks:2",
          [ 6 ] = "minecraft:planks:2",
        },
        count = 1,
      },
      [ "minecraft:bread:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:wheat:0",
          "minecraft:wheat:0",
          "minecraft:wheat:0",
        },
      },
      [ "minecraft:banner:12" ] = {
        ingredients = {
          "minecraft:wool:3",
          "minecraft:wool:3",
          "minecraft:wool:3",
          [ 6 ] = "minecraft:wool:3",
          [ 7 ] = "minecraft:wool:3",
          [ 5 ] = "minecraft:wool:3",
          [ 10 ] = "minecraft:stick:0",
        },
        count = 1,
        maxCount = 16,
      },
      [ "minecraft:golden_helmet:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:wooden_shovel:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:planks:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:painting:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:stick:0",
          "minecraft:stick:0",
          "minecraft:stick:0",
          [ 7 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
          [ 10 ] = "minecraft:stick:0",
          [ 11 ] = "minecraft:stick:0",
          [ 5 ] = "minecraft:stick:0",
          [ 6 ] = "minecraft:wool:0",
        },
      },
      [ "minecraft:concrete_powder:2" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:13",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:stained_hardened_clay:4" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:11",
        },
      },
      [ "minecraft:iron_leggings:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:golden_shovel:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:boat:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:planks:0",
          [ 3 ] = "minecraft:planks:0",
          [ 7 ] = "minecraft:planks:0",
          [ 5 ] = "minecraft:planks:0",
          [ 6 ] = "minecraft:planks:0",
        },
        count = 1,
      },
      [ "minecraft:wooden_sword:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:planks:0",
          [ 5 ] = "minecraft:planks:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:furnace_minecart:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:furnace:0",
          [ 5 ] = "minecraft:minecart:0",
        },
        count = 1,
      },
      [ "minecraft:iron_hoe:0" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
        },
      },
      [ "minecraft:speckled_melon:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_nugget:0",
          "minecraft:gold_nugget:0",
          "minecraft:gold_nugget:0",
          [ 7 ] = "minecraft:gold_nugget:0",
          [ 9 ] = "minecraft:gold_nugget:0",
          [ 10 ] = "minecraft:gold_nugget:0",
          [ 11 ] = "minecraft:gold_nugget:0",
          [ 5 ] = "minecraft:gold_nugget:0",
          [ 6 ] = "minecraft:melon:0",
        },
      },
      [ "minecraft:stained_hardened_clay:8" ] = {
        count = 8,
        ingredients = {
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          "minecraft:hardened_clay:0",
          [ 7 ] = "minecraft:hardened_clay:0",
          [ 9 ] = "minecraft:hardened_clay:0",
          [ 10 ] = "minecraft:hardened_clay:0",
          [ 11 ] = "minecraft:hardened_clay:0",
          [ 5 ] = "minecraft:hardened_clay:0",
          [ 6 ] = "minecraft:dye:7",
        },
      },
      [ "minecraft:concrete_powder:5" ] = {
        count = 8,
        ingredients = {
          "minecraft:dye:10",
          "minecraft:sand:0",
          "minecraft:sand:0",
          [ 7 ] = "minecraft:gravel:0",
          [ 9 ] = "minecraft:gravel:0",
          [ 10 ] = "minecraft:gravel:0",
          [ 11 ] = "minecraft:gravel:0",
          [ 5 ] = "minecraft:sand:0",
          [ 6 ] = "minecraft:sand:0",
        },
      },
      [ "minecraft:item_frame:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:stick:0",
          "minecraft:stick:0",
          "minecraft:stick:0",
          [ 7 ] = "minecraft:stick:0",
          [ 9 ] = "minecraft:stick:0",
          [ 10 ] = "minecraft:stick:0",
          [ 11 ] = "minecraft:stick:0",
          [ 5 ] = "minecraft:stick:0",
          [ 6 ] = "minecraft:leather:0",
        },
      },
      [ "minecraft:nether_wart_block:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:nether_wart:0",
          "minecraft:nether_wart:0",
          "minecraft:nether_wart:0",
          [ 7 ] = "minecraft:nether_wart:0",
          [ 9 ] = "minecraft:nether_wart:0",
          [ 10 ] = "minecraft:nether_wart:0",
          [ 11 ] = "minecraft:nether_wart:0",
          [ 5 ] = "minecraft:nether_wart:0",
          [ 6 ] = "minecraft:nether_wart:0",
        },
      },
      [ "minecraft:iron_boots:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
      },
      [ "minecraft:carrot_on_a_stick:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:fishing_rod:0",
          [ 6 ] = "minecraft:carrot:0",
        },
        count = 1,
      },
      [ "minecraft:shield:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:planks:0",
          "minecraft:iron_ingot:0",
          "minecraft:planks:0",
          [ 6 ] = "minecraft:planks:0",
          [ 7 ] = "minecraft:planks:0",
          [ 5 ] = "minecraft:planks:0",
          [ 10 ] = "minecraft:planks:0",
        },
        count = 1,
      },
      [ "minecraft:cake:0" ] = {
        count = 1,
        maxCount = 16,
        ingredients = {
          "minecraft:milk_bucket:0",
          "minecraft:milk_bucket:0",
          "minecraft:milk_bucket:0",
          [ 7 ] = "minecraft:sugar:0",
          [ 9 ] = "minecraft:wheat:0",
          [ 10 ] = "minecraft:wheat:0",
          [ 11 ] = "minecraft:wheat:0",
          [ 5 ] = "minecraft:sugar:0",
          [ 6 ] = "minecraft:egg:0",
        },
      },
    },
    name = "minecraft_1-12",
    version = "1.12",
  },
  names = {
    [ "minecraft:0" ] = "No Information Avaliable",
  },
}
