{
  recipes = {
    recipes = {
      [ "computercraft:turtle_advanced:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:chest:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "computercraft:computer:16384",
        },
      },
      [ "computercraft:turtle_advanced:0:6706fc084e137705227fcc54ef7c2308" ] = {
        count = 1,
        ingredients = {
          "computercraft:peripheral:5",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:computer:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:glass_pane:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:redstone:0",
        },
      },
      [ "computercraft:computer:16384" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:glass_pane:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:redstone:0",
        },
      },
      [ "computercraft:disk_expanded:0:27e3120fac06bb35c87b11851d07bd20" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:redstone:0",
          "minecraft:paper:0",
        },
        count = 1,
      },
      [ "computercraft:turtle_advanced:0:43099deefb7332a34b4dfb3e35e2eba3" ] = {
        count = 1,
        ingredients = {
          "computercraft:peripheral:1",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:pocket_computer:0:5844ab7f21a1db2436ba586e4b875eae" ] = {
        maxCount = 1,
        ingredients = {
          "computercraft:peripheral:1",
          [ 5 ] = "computercraft:pocket_computer:0:e4a913114a0efbf80c2de6f3697b3187",
        },
        count = 1,
      },
      [ "computercraft:turtle_advanced:0:ae2dad8f0eacea469dcbb35c5e4d0d8d" ] = {
        count = 1,
        ingredients = {
          "computercraft:advanced_modem:0",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:pocket_computer:1:347325c877e3e1c7d19a2b09b713684d" ] = {
        maxCount = 1,
        ingredients = {
          "computercraft:advanced_modem:0",
          [ 5 ] = "computercraft:pocket_computer:1:9926aa5028afe831247d31b4276c72c0",
        },
        count = 1,
      },
      [ "computercraft:turtle_advanced:0:19d60dd2b95ed827e2a9e68b3c2247e9" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_hoe:0",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:pocket_computer:1:42e1f5f8128d63cb0c4daa1be9956c09" ] = {
        maxCount = 1,
        ingredients = {
          "computercraft:peripheral:1",
          [ 5 ] = "computercraft:pocket_computer:1:9926aa5028afe831247d31b4276c72c0",
        },
        count = 1,
      },
      [ "computercraft:turtle_advanced:0:447f40255d934fb1611683616b3fe845" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_sword:0",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:peripheral:2" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:stone:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:glass_pane:0",
        },
      },
      [ "computercraft:turtle_expanded:0:cbd68d4ad8ecd18cf0f264a49c9b75d8" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_axe:0",
          "computercraft:turtle_expanded:0",
        },
      },
      [ "computercraft:pocket_computer:0:239ceec77b09da86ecd2f3784c0d8a83" ] = {
        maxCount = 1,
        ingredients = {
          "computercraft:peripheral:5",
          [ 5 ] = "computercraft:pocket_computer:0:4c60b32731e91e93e03f5e6d50f5b16e",
        },
        count = 1,
      },
      [ "computercraft:turtle_advanced:0:233651af671416917f07f5e239ff60a5" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_pickaxe:0",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:peripheral:5" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:redstone:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:noteblock:0",
        },
      },
      [ "computercraft:turtle_expanded:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:chest:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "computercraft:computer:0",
        },
      },
      [ "computercraft:peripheral:3" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:dye:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:glass_pane:0",
        },
      },
      [ "computercraft:peripheral:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:redstone:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:redstone:0",
        },
      },
      [ "computercraft:turtle_expanded:0:447f40255d934fb1611683616b3fe845" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_sword:0",
          "computercraft:turtle_expanded:0",
        },
      },
      [ "computercraft:cable:0" ] = {
        count = 6,
        ingredients = {
          [ 7 ] = "minecraft:stone:0",
          [ 2 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:redstone:0",
        },
      },
      [ "computercraft:turtle_expanded:0:052734a2e0c2bd127df9dfd93e12fc30" ] = {
        count = 1,
        ingredients = {
          "minecraft:crafting_table:0",
          "computercraft:turtle_expanded:0",
        },
      },
      [ "computercraft:turtle_expanded:0:19d60dd2b95ed827e2a9e68b3c2247e9" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_hoe:0",
          "computercraft:turtle_expanded:0",
        },
      },
      [ "computercraft:turtle_expanded:0:83b62587be0b0630f092ce42faaa3695" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_shovel:0",
          "computercraft:turtle_expanded:0",
        },
      },
      [ "computercraft:turtle_advanced:0:83b62587be0b0630f092ce42faaa3695" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_shovel:0",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:turtle_expanded:0:233651af671416917f07f5e239ff60a5" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_pickaxe:0",
          "computercraft:turtle_expanded:0",
        },
      },
      [ "computercraft:turtle_advanced:0:052734a2e0c2bd127df9dfd93e12fc30" ] = {
        count = 1,
        ingredients = {
          "minecraft:crafting_table:0",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:cable:1" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:stone:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:redstone:0",
        },
      },
      [ "computercraft:pocket_computer:1:e7c2e613630dac248a84323797e97bb7" ] = {
        maxCount = 1,
        ingredients = {
          "computercraft:peripheral:5",
          [ 5 ] = "computercraft:pocket_computer:1:9926aa5028afe831247d31b4276c72c0",
        },
        count = 1,
      },
      [ "computercraft:advanced_modem:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:ender_eye:0",
        },
      },
      [ "computercraft:command_computer:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:glass_pane:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:command_block:0",
        },
      },
      [ "computercraft:pocket_computer:1" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:glass_pane:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:golden_apple:0",
        },
        count = 1,
      },
      [ "computercraft:turtle_advanced:0:cbd68d4ad8ecd18cf0f264a49c9b75d8" ] = {
        count = 1,
        ingredients = {
          "minecraft:diamond_axe:0",
          "computercraft:turtle_advanced:0",
        },
      },
      [ "computercraft:pocket_computer:0" ] = {
        maxCount = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:glass_pane:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:golden_apple:0",
        },
        count = 1,
      },
      [ "computercraft:peripheral:4" ] = {
        count = 4,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "minecraft:glass_pane:0",
        },
      },
      [ "computercraft:peripheral:1" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:stone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:stone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:stone:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:ender_pearl:0",
        },
      },
      [ "computercraft:pocket_computer:0:22ef6d03d7dcdaa35a4d54dfd085abd7" ] = {
        maxCount = 1,
        ingredients = {
          "computercraft:advanced_modem:0",
          [ 5 ] = "computercraft:pocket_computer:0:e4a913114a0efbf80c2de6f3697b3187",
        },
        count = 1,
      },
    },
    name = "cc-tweaked",
    version = "MC 1.12",
  },
  names = {
    [ "computercraft:turtle_advanced:0" ] = "Advanced Turtle",
    [ "computercraft:turtle_advanced:0:6706fc084e137705227fcc54ef7c2308" ] = "Advanced Noisy Turtle",
    [ "computercraft:computer:0" ] = "Computer",
    [ "computercraft:peripheral:4" ] = "Advanced Monitor",
    [ "computercraft:disk_expanded:0:27e3120fac06bb35c87b11851d07bd20" ] = "Floppy Disk",
    [ "computercraft:turtle_advanced:0:43099deefb7332a34b4dfb3e35e2eba3" ] = "Advanced Wireless Turtle",
    [ "computercraft:peripheral:1" ] = "Wireless Modem",
    [ "computercraft:turtle_advanced:0:ae2dad8f0eacea469dcbb35c5e4d0d8d" ] = "Advanced Ender Turtle",
    [ "computercraft:pocket_computer:1:347325c877e3e1c7d19a2b09b713684d" ] = "Advanced Ender Pocket Computer",
    [ "computercraft:turtle_advanced:0:19d60dd2b95ed827e2a9e68b3c2247e9" ] = "Advanced Farming Turtle",
    [ "computercraft:pocket_computer:1:42e1f5f8128d63cb0c4daa1be9956c09" ] = "Advanced Wireless Pocket Computer",
    [ "computercraft:turtle_advanced:0:447f40255d934fb1611683616b3fe845" ] = "Advanced Melee Turtle",
    [ "computercraft:peripheral:2" ] = "Monitor",
    [ "computercraft:turtle_expanded:0:cbd68d4ad8ecd18cf0f264a49c9b75d8" ] = "Felling Turtle",
    [ "computercraft:pocket_computer:0:239ceec77b09da86ecd2f3784c0d8a83" ] = "Noisy Pocket Computer",
    [ "computercraft:turtle_advanced:0:233651af671416917f07f5e239ff60a5" ] = "Advanced Mining Turtle",
    [ "computercraft:peripheral:5" ] = "Speaker",
    [ "computercraft:turtle_expanded:0" ] = "Turtle",
    [ "computercraft:peripheral:3" ] = "Printer",
    [ "computercraft:peripheral:0" ] = "Disk Drive",
    [ "computercraft:turtle_expanded:0:447f40255d934fb1611683616b3fe845" ] = "Melee Turtle",
    [ "computercraft:cable:0" ] = "Networking Cable",
    [ "computercraft:turtle_expanded:0:052734a2e0c2bd127df9dfd93e12fc30" ] = "Crafty Turtle",
    [ "computercraft:turtle_expanded:0:19d60dd2b95ed827e2a9e68b3c2247e9" ] = "Farming Turtle",
    [ "computercraft:command_computer:0" ] = "Command Computer",
    [ "computercraft:turtle_advanced:0:83b62587be0b0630f092ce42faaa3695" ] = "Advanced Digging Turtle",
    [ "computercraft:turtle_expanded:0:233651af671416917f07f5e239ff60a5" ] = "Mining Turtle",
    [ "computercraft:advanced_modem:0" ] = "Ender Modem",
    [ "computercraft:pocket_computer:0:4c60b32731e91e93e03f5e6d50f5b16e" ] = "Pocket Computer",
    [ "computercraft:pocket_computer:1:e7c2e613630dac248a84323797e97bb7" ] = "Advanced Noisy Pocket Computer",
    [ "computercraft:pocket_computer:1:9926aa5028afe831247d31b4276c72c0" ] = "Advanced Pocket Computer",
    [ "computercraft:computer:16384" ] = "Advanced Computer",
    [ "computercraft:turtle_expanded:0:83b62587be0b0630f092ce42faaa3695" ] = "Digging Turtle",
    [ "computercraft:turtle_advanced:0:cbd68d4ad8ecd18cf0f264a49c9b75d8" ] = "Advanced Felling Turtle",
    [ "computercraft:cable:1" ] = "Wired Modem",
    [ "computercraft:pocket_computer:0:5844ab7f21a1db2436ba586e4b875eae" ] = "Wireless Pocket Computer",
    [ "computercraft:turtle_advanced:0:052734a2e0c2bd127df9dfd93e12fc30" ] = "Advanced Crafty Turtle",
    [ "computercraft:pocket_computer:0:22ef6d03d7dcdaa35a4d54dfd085abd7" ] = "Ender Pocket Computer",
  },
}
