{
  recipes = {
    recipes = {
      [ "plethora:manipulator:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:glass:0",
          "minecraft:gold_ingot:0",
          "minecraft:glass:0",
          [ 7 ] = "minecraft:redstone:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:redstone:0",
          [ 6 ] = "computercraft:cable:1",
        },
      },
      [ "plethora:module:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:ender_chest:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:ender_chest:0",
          [ 9 ] = "minecraft:gold_ingot:0",
          [ 10 ] = "minecraft:ender_chest:0",
          [ 11 ] = "minecraft:gold_ingot:0",
          [ 5 ] = "minecraft:ender_chest:0",
          [ 6 ] = "minecraft:diamond_helmet:0",
        },
      },
      [ "plethora:module:1" ] = {
        count = 1,
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:diamond:0",
          [ 7 ] = "minecraft:enchanted_book:0:b0d8fbb298abe27149d691b336ad574d",
          [ 5 ] = "minecraft:glass:0",
          [ 11 ] = "minecraft:iron_ingot:0",
        },
      },
      [ "plethora:neuralconnector:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 7 ] = "minecraft:redstone:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 3 ] = "minecraft:redstone:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:ender_pearl:0",
        },
        count = 1,
      },
      [ "plethora:module:3" ] = {
        count = 1,
        ingredients = {
          "minecraft:ender_eye:0",
          "minecraft:rotten_flesh:0",
          "minecraft:ender_eye:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:observer:0",
        },
      },
      [ "plethora:manipulator:1" ] = {
        count = 1,
        ingredients = {
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          "minecraft:gold_ingot:0",
          [ 7 ] = "minecraft:redstone:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:redstone:0",
          [ 6 ] = "plethora:manipulator:0",
        },
      },
      [ "plethora:redstone_integrator:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:stone:0",
          "minecraft:redstone:0",
          "minecraft:stone:0",
          [ 7 ] = "minecraft:redstone:0",
          [ 9 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:redstone:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:redstone:0",
          [ 6 ] = "computercraft:cable:0",
        },
      },
      [ "plethora:module:2" ] = {
        count = 1,
        ingredients = {
          "minecraft:ender_eye:0",
          "minecraft:dirt:0",
          "minecraft:ender_eye:0",
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "minecraft:observer:0",
        },
      },
      [ "plethora:module:4" ] = {
        count = 1,
        ingredients = {
          "minecraft:redstone:0",
          "minecraft:gold_ingot:0",
          "minecraft:redstone:0",
          [ 7 ] = "minecraft:piston:0",
          [ 9 ] = "minecraft:redstone:0",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "minecraft:redstone:0",
          [ 5 ] = "minecraft:piston:0",
          [ 6 ] = "minecraft:potion:0:23a2e7a760bef7f699b61346d102e27d",
        },
      },
      [ "plethora:module:5" ] = {
        count = 1,
        ingredients = {
          [ 7 ] = "minecraft:noteblock:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 2 ] = "minecraft:redstone:0",
          [ 3 ] = "minecraft:stone:0",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:wool:0",
          [ 6 ] = "minecraft:redstone:0",
          [ 9 ] = "minecraft:iron_ingot:0",
        },
      },
      [ "plethora:neuralinterface:0:18ab2e02cbb0976e3cadeb7cd10e49b8" ] = {
        maxCount = 1,
        ingredients = {
          [ 7 ] = "minecraft:redstone:0",
          [ 3 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "computercraft:cable:1",
          [ 5 ] = "minecraft:iron_ingot:0",
          [ 6 ] = "computercraft:pocket_computer:1:eb4fa32f62bfe9b2fd59cecd2404ab15",
          [ 10 ] = "minecraft:gold_ingot:0",
        },
        count = 1,
      },
      [ "plethora:keyboard:0" ] = {
        maxCount = 1,
        ingredients = {
          [ 7 ] = "minecraft:iron_ingot:0",
          [ 9 ] = "minecraft:stone:0",
          [ 3 ] = "computercraft:peripheral:1",
          [ 11 ] = "minecraft:stone:0",
          [ 5 ] = "minecraft:stone:0",
          [ 6 ] = "minecraft:stone:0",
          [ 10 ] = "minecraft:stone:0",
        },
        count = 1,
      },
      [ "plethora:module:6" ] = {
        count = 1,
        ingredients = {
          "computercraft:peripheral:1",
          "minecraft:iron_ingot:0",
          "computercraft:peripheral:1",
          [ 7 ] = "computercraft:peripheral:4",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_helmet:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "computercraft:peripheral:4",
          [ 6 ] = "computercraft:peripheral:4",
        },
      },
    },
    name = "plethora",
    version = "MC 1.12",
  },
  names = {
    [ "plethora:manipulator:0" ] = "Manipulator Mk I",
    [ "plethora:module:3" ] = "Entity sensor",
    [ "plethora:module:5" ] = "Chat recorder",
    [ "plethora:neuralconnector:0" ] = "Neural connector",
    [ "plethora:module:0" ] = "Introspection module",
    [ "plethora:manipulator:1" ] = "Manipulator Mk II",
    [ "plethora:redstone_integrator:0" ] = "Redstone integrator",
    [ "plethora:module:2" ] = "Block scanner",
    [ "plethora:module:4" ] = "Kinetic augment",
    [ "plethora:module:6" ] = "Overlay glasses",
    [ "plethora:neuralinterface:0:18ab2e02cbb0976e3cadeb7cd10e49b8" ] = "Neural interface",
    [ "plethora:keyboard:0" ] = "Keyboard",
    [ "plethora:module:1" ] = "Frickin' laser beam",
  },
}
