{
  recipes = {
    recipes = {
      [ "mekanismgenerators:generator:8" ] = {
        count = 1,
        ingredients = {
          "mekanism:ingot:4",
          "mekanism:enrichedalloy:0",
          "mekanism:ingot:4",
          [ 7 ] = "mekanism:controlcircuit:1",
          [ 9 ] = "mekanism:ingot:4",
          [ 10 ] = "mekanism:enrichedalloy:0",
          [ 11 ] = "mekanism:ingot:4",
          [ 5 ] = "mekanism:controlcircuit:1",
          [ 6 ] = "mekanism:enrichedalloy:0",
        },
      },
      [ "mekanismgenerators:generator:4" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "minecraft:redstone:0",
          "mekanism:enrichedalloy:0",
          "minecraft:redstone:0",
          [ 7 ] = "mekanism:biofuel:0",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "mekanism:enrichedalloy:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "mekanism:biofuel:0",
          [ 6 ] = "mekanism:controlcircuit:0",
        },
      },
      [ "mekanismgenerators:reactorglass:1" ] = {
        count = 2,
        ingredients = {
          [ 7 ] = "mekanismgenerators:reactorglass:0",
          [ 2 ] = "mekanismgenerators:reactorglass:0",
          [ 10 ] = "mekanismgenerators:reactorglass:0",
          [ 5 ] = "mekanismgenerators:reactorglass:0",
          [ 6 ] = "minecraft:redstone_block:0",
        },
      },
      [ "mekanismgenerators:generator:5:bc87dcc98081ec10951d587241b94400" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "mekanismgenerators:generator:1",
          "mekanism:enrichedalloy:0",
          "mekanismgenerators:generator:1",
          [ 7 ] = "mekanismgenerators:generator:1",
          [ 9 ] = "minecraft:iron_ingot:0",
          [ 10 ] = "minecraft:iron_ingot:0",
          [ 11 ] = "minecraft:iron_ingot:0",
          [ 5 ] = "mekanismgenerators:generator:1",
          [ 6 ] = "mekanism:enrichedalloy:0",
        },
      },
      [ "mekanismgenerators:reactor:3" ] = {
        count = 1,
        ingredients = {
          [ 7 ] = "minecraft:redstone:0",
          [ 2 ] = "minecraft:redstone:0",
          [ 10 ] = "minecraft:redstone:0",
          [ 5 ] = "minecraft:redstone:0",
          [ 6 ] = "mekanismgenerators:reactor:1",
        },
      },
      [ "mekanismgenerators:generator:7" ] = {
        count = 1,
        ingredients = {
          "mekanism:ingot:4",
          "mekanism:enrichedalloy:0",
          "mekanism:ingot:4",
          [ 7 ] = "mekanism:ingot:4",
          [ 9 ] = "mekanism:ingot:4",
          [ 10 ] = "mekanism:enrichedalloy:0",
          [ 11 ] = "mekanism:ingot:4",
          [ 5 ] = "mekanism:ingot:4",
          [ 6 ] = "mekanism:enrichedalloy:0",
        },
      },
      [ "mekanismgenerators:reactorglass:0" ] = {
        count = 4,
        ingredients = {
          [ 7 ] = "mekanismgenerators:reactor:1",
          [ 2 ] = "mekanismgenerators:reactor:1",
          [ 10 ] = "mekanismgenerators:reactor:1",
          [ 5 ] = "mekanismgenerators:reactor:1",
          [ 6 ] = "minecraft:glass:0",
        },
      },
      [ "mekanismgenerators:generator:6" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          [ 7 ] = "mekanism:ingot:1",
          [ 2 ] = "mekanism:ingot:1",
          [ 10 ] = "mekanism:controlcircuit:0",
          [ 11 ] = "mekanism:energytablet:0",
          [ 5 ] = "mekanism:ingot:1",
          [ 6 ] = "mekanism:enrichedalloy:0",
          [ 9 ] = "mekanism:energytablet:0",
        },
      },
      [ "mekanismgenerators:generator:1" ] = {
        ingredients = {
          "mekanismgenerators:solarpanel:0",
          "mekanismgenerators:solarpanel:0",
          "mekanismgenerators:solarpanel:0",
          [ 7 ] = "mekanism:enrichedalloy:0",
          [ 9 ] = "mekanism:dust:2",
          [ 10 ] = "mekanism:energytablet:0",
          [ 11 ] = "mekanism:dust:2",
          [ 5 ] = "mekanism:enrichedalloy:0",
          [ 6 ] = "minecraft:iron_ingot:0",
        },
        count = 1,
        maxCount = 1,
      },
      [ "mekanismgenerators:reactor:0" ] = {
        count = 1,
        ingredients = {
          "mekanism:controlcircuit:3",
          "minecraft:glass_pane:0",
          "mekanism:controlcircuit:3",
          [ 7 ] = "mekanismgenerators:reactor:1",
          [ 9 ] = "mekanismgenerators:reactor:1",
          [ 10 ] = "mekanismgenerators:reactor:1",
          [ 11 ] = "mekanismgenerators:reactor:1",
          [ 5 ] = "mekanismgenerators:reactor:1",
          [ 6 ] = "mekanism:gastank:0:96f2d2e6051925f89c2621674c3ef20d",
        },
      },
      [ "mekanismgenerators:generator:9" ] = {
        count = 1,
        ingredients = {
          "mekanism:ingot:4",
          "minecraft:gold_ingot:0",
          "mekanism:ingot:4",
          [ 7 ] = "minecraft:gold_ingot:0",
          [ 9 ] = "mekanism:ingot:4",
          [ 10 ] = "minecraft:gold_ingot:0",
          [ 11 ] = "mekanism:ingot:4",
          [ 5 ] = "minecraft:gold_ingot:0",
          [ 6 ] = "mekanism:energytablet:0",
        },
      },
      [ "mekanismgenerators:generator:3" ] = {
        count = 1,
        maxCount = 1,
        ingredients = {
          "mekanism:ingot:1",
          "mekanism:enrichedalloy:0",
          "mekanism:ingot:1",
          [ 7 ] = "mekanism:basicblock:8",
          [ 9 ] = "mekanism:ingot:1",
          [ 10 ] = "mekanism:enrichedalloy:0",
          [ 11 ] = "mekanism:ingot:1",
          [ 5 ] = "mekanism:basicblock:8",
          [ 6 ] = "mekanism:electrolyticcore:0",
        },
      },
      [ "mekanismgenerators:solarpanel:0" ] = {
        count = 1,
        ingredients = {
          "minecraft:glass_pane:0",
          "minecraft:glass_pane:0",
          "minecraft:glass_pane:0",
          [ 7 ] = "minecraft:redstone:0",
          [ 9 ] = "mekanism:ingot:1",
          [ 10 ] = "mekanism:ingot:1",
          [ 11 ] = "mekanism:ingot:1",
          [ 5 ] = "minecraft:redstone:0",
          [ 6 ] = "mekanism:enrichedalloy:0",
        },
      },
      [ "mekanismgenerators:reactor:2" ] = {
        count = 2,
        ingredients = {
          [ 7 ] = "mekanismgenerators:reactor:1",
          [ 2 ] = "mekanismgenerators:reactor:1",
          [ 10 ] = "mekanismgenerators:reactor:1",
          [ 5 ] = "mekanismgenerators:reactor:1",
          [ 6 ] = "mekanism:controlcircuit:3",
        },
      },
      [ "mekanismgenerators:generator:12" ] = {
        count = 2,
        ingredients = {
          [ 7 ] = "mekanismgenerators:generator:10",
          [ 2 ] = "mekanismgenerators:generator:10",
          [ 10 ] = "mekanismgenerators:generator:10",
          [ 5 ] = "mekanismgenerators:generator:10",
          [ 6 ] = "minecraft:iron_bars:0",
        },
      },
      [ "mekanismgenerators:turbineblade:0" ] = {
        count = 1,
        ingredients = {
          [ 7 ] = "mekanism:ingot:4",
          [ 2 ] = "mekanism:ingot:4",
          [ 10 ] = "mekanism:ingot:4",
          [ 5 ] = "mekanism:ingot:4",
          [ 6 ] = "mekanism:enrichedalloy:0",
        },
      },
      [ "mekanismgenerators:generator:10" ] = {
        count = 4,
        ingredients = {
          [ 7 ] = "mekanism:ingot:4",
          [ 2 ] = "mekanism:ingot:4",
          [ 10 ] = "mekanism:ingot:4",
          [ 5 ] = "mekanism:ingot:4",
          [ 6 ] = "mekanism:ingot:1",
        },
      },
      [ "mekanismgenerators:reactor:1" ] = {
        count = 4,
        ingredients = {
          [ 7 ] = "mekanism:basicblock:8",
          [ 2 ] = "mekanism:basicblock:8",
          [ 10 ] = "mekanism:basicblock:8",
          [ 5 ] = "mekanism:basicblock:8",
          [ 6 ] = "mekanism:atomicalloy:0",
        },
      },
      [ "mekanismgenerators:generator:13" ] = {
        count = 1,
        ingredients = {
          "mekanism:ingot:4",
          "mekanism:ingot:6",
          "mekanism:ingot:4",
          [ 7 ] = "mekanism:ingot:6",
          [ 9 ] = "mekanism:ingot:4",
          [ 10 ] = "mekanism:ingot:6",
          [ 11 ] = "mekanism:ingot:4",
          [ 5 ] = "mekanism:ingot:6",
          [ 6 ] = "minecraft:bucket:0",
        },
      },
      [ "mekanismgenerators:generator:0" ] = {
        ingredients = {
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          "minecraft:iron_ingot:0",
          [ 7 ] = "minecraft:planks:0",
          [ 9 ] = "mekanism:ingot:5",
          [ 10 ] = "minecraft:furnace:0",
          [ 11 ] = "mekanism:ingot:5",
          [ 5 ] = "minecraft:planks:0",
          [ 6 ] = "mekanism:ingot:1",
        },
        count = 1,
        maxCount = 1,
      },
      [ "mekanismgenerators:generator:11:bc87dcc98081ec10951d587241b94400" ] = {
        count = 2,
        ingredients = {
          [ 7 ] = "mekanismgenerators:generator:10",
          [ 2 ] = "mekanismgenerators:generator:10",
          [ 10 ] = "mekanismgenerators:generator:10",
          [ 5 ] = "mekanismgenerators:generator:10",
          [ 6 ] = "mekanism:controlcircuit:1",
        },
      },
    },
    name = "Mekanism: Generators",
    version = "MC 1.12",
  },
  names = {
    [ "mekanismgenerators:reactor:0" ] = "Reactor Controller",
    [ "mekanismgenerators:generator:4" ] = "Bio-Generator",
    [ "mekanismgenerators:reactorglass:1" ] = "Laser Focus Matrix",
    [ "mekanismgenerators:generator:5:bc87dcc98081ec10951d587241b94400" ] = "Advanced Solar Generator",
    [ "mekanismgenerators:reactor:3" ] = "Reactor Logic Adapter",
    [ "mekanismgenerators:generator:0" ] = "Heat Generator",
    [ "mekanismgenerators:generator:7" ] = "Turbine Rotor",
    [ "mekanismgenerators:generator:6" ] = "Wind Generator",
    [ "mekanismgenerators:generator:9" ] = "Electromagnetic Coil",
    [ "mekanismgenerators:reactorglass:0" ] = "Reactor Glass",
    [ "mekanismgenerators:generator:8" ] = "Rotational Complex",
    [ "mekanismgenerators:generator:10" ] = "Turbine Casing",
    [ "mekanismgenerators:turbineblade:0" ] = "Turbine Blade",
    [ "mekanismgenerators:reactor:2" ] = "Reactor Port",
    [ "mekanismgenerators:reactor:1" ] = "Reactor Frame",
    [ "mekanismgenerators:generator:3" ] = "Gas-Burning Generator",
    [ "mekanismgenerators:generator:1" ] = "Solar Generator",
    [ "mekanismgenerators:solarpanel:0" ] = "Solar Panel",
    [ "mekanismgenerators:generator:13" ] = "Saturating Condenser",
    [ "mekanismgenerators:generator:12" ] = "Turbine Vent",
    [ "mekanismgenerators:generator:11:bc87dcc98081ec10951d587241b94400" ] = "Turbine Valve",
  },
}
